### ISSUE TITLE
Give everyone access to the leader board.

### ISSUE THREAD

**Issue by MilesBowker** [jacogreyling/pexeso#82]

**Comment by jacogreyling** [comment]
We will create a leaderboard for all participants.

**Comment by CA-CharlKlein** [comment]
Should we create a new Public Page ? Possibly theme-able

**Comment by jacogreyling** [comment]
Expose the 'top 10' leaderboard under /account/leaderboard for each user. This should be a generic leaderboard ('top 10') taking the 'event' into account. Events are setup on the setting page /account/settings.

**Comment by jacogreyling** [comment]
Please update your leaderboard to take the 'event' into account for searching the top 10 entries. If you look at pages/admin/leaderboard/actions.js there is a new static method you can re-use called 'retrieveTopTenForEvent'. Just pass it the name of the event from the Account document and the rest should fall in place.
