### ISSUE TITLE
Dockerize Application

### ISSUE THREAD

**Issue by CharlKlein** [jacogreyling/pexeso#84]

**Comment by agathver** [comment]
I would like to help with this one. I also see there is #55 which can be solved if docker is used.

**Comment by CA-CharlKlein** [comment]
Hi Amitosh, 
Sorry for the delayed response,
 You are more than Welcome to assist with this enhancement. 

I've tested lightly using the node:8.7.0-alpine - base image. 
 You will need to create a custom run-first-time script for the mongo DB config, 

I have a docker-compose.yml that I started working on, Attached for your reference 
[docker-compose.yml.zip](https://github.com/jacogreyling/pexeso/files/1390838/docker-compose.yml.zip)

Thanks
Charl

**Comment by CA-CharlKlein** [comment]
@edwinmkm - Please Register for a Heroku account and Let me know once done
